# Generated by Django 4.1.4 on 2023-03-20 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Twitts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitt_header', models.TextField(null=True, verbose_name='Twitt Konusu')),
                ('twitt', models.TextField(max_length=150, verbose_name='Twitt yazısı')),
                ('like', models.IntegerField(verbose_name='Like sayısı')),
                ('retweet', models.IntegerField(verbose_name='RT sayısı')),
                ('media', models.ImageField(null=True, upload_to=None, verbose_name='Twitt Media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=150, verbose_name='Yorumlar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
