# Generated by Django 4.1.4 on 2023-03-20 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_twitts_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitts',
            name='userinfo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.userinfo', verbose_name='Userinfo'),
        ),
    ]
